/*
 * ourchildren.js
 * 
 * copyright (c) 2009, Diego Che
 *
 * For our children.
 */
 
(function() {
     
this.OurChildren = {
    children: [],  // has been parse and generated by a Ruby script.
    
    // Names are splitted into multiple lists to reduce display time.
    listNumber: 1,
    
    p: null,
    
    initCanvas: function() {
        this.p = Processing("sky");
        this.p.size(700, 100);
    },
    
    riseAStar: function() {
        if (this.children.length == 0) {
            return;
        }
        var i = this.randomInt(this.children.length);
        var child = this.children[i];
        var div = this.buildName(child);
        
        var speed = this.lifeSpan(child.age) + this.randomInt(2000);
        var height = $('#stars:first').height() - 60;
        var width = $('#stars:first').width();
        
        var hor = this.randomInt(width);
        if (hor * 2 > width) {
            $(div).css('right', (width - hor).toString() + 'px');
        } else {
            $(div).css('left', hor.toString() + 'px')
        }
        
        $('#stars').append($(div));
        $(div).oneTime(speed, function() {
            $(this).remove();
            OurChildren.starShines();
        });
        $(div).hover(function() {
            $(this).queue('fx', []);
            $(this).stop();
            $(this).stopTime();
            $(this).animate({opacity: 1.0}, 200);
        }, function() {
            var bottom = height + 60 - $(this).position().top - $(this).height();
            var newSpeed = speed * (height - bottom) / height
            $(this).oneTime(newSpeed, function() {
                $(this).remove();
            });
            $(this).animate({
                bottom: '+='.concat(height - bottom),
                opacity: 0.0
            }, newSpeed);
        });
        $(div).animate({
                bottom:'+='.concat(height / 2),
                opacity:1.0
            },speed / 2);
        $(div).animate({
                bottom:'+='.concat(height / 2),
                opacity:0.0
            },speed / 2);
    },
    
    // return an Array of random ordered numbers, shuffled by Knuth algorithm.
    shuffleList: function(number) {
        var na = [];
        var i = 0;
        while (i < number) {
            na.push(i++);
        }
        
        i = number;
        while (i > 2) {
            var r = this.randomInt() + 1;
            if (i != r) {
                var o = na[i - 1];
                na[i - 1] = na[r - 1];
                na[r - 1] = o;
                i--;
            }
        }
        return na;
    },
    
    randomInt: function(upper) {
        return Math.floor(Math.random() * upper);
    },
    
    lifeSpan: function(age) {
        if (typeof age != 'number' || isNaN(age) || age <= 0) {
            return 6000;
        }
        return 2000 + age * 200;
    },
    
    genderColor: function(gender) {
        return (gender == "male") ? ("#ddddff") : ("#ffffff");
    },
    
    ageString: function(age) {
        if (typeof age != 'number' || isNaN(age) || age <= 0) {
            return null;
        }
        return age.toString() + "岁";
    },
    
    // draw a star using Processing.js
    starShines: function(pos) {
    },
    
    buildName: function(child) {
        var div = $('<div/>').attr('class', 'child');
        var name = $('<span/>').attr('class', 'name').text(child.name).css('color', this.genderColor(child.gender));
        var age = $('<span/>').attr('class', 'age').text(this.ageString(child.age));
        var infoDiv = $('<div/>').attr('class', 'info');
        
        return $(div).append(name).append(age);
    },
    
    downloadNames: function() {
        var na = this.shuffleList(this.listNumber);
        var fn = function(data) {
            jQuery.merge(OurChildren.children, data.children);
        };
        
        for (var i = 0; i < this.listNumber; i++) {
            jQuery.getJSON("names/OurChildren".concat(na[i]).concat(".json"), fn);
        }
    }
};

OurChildren.downloadNames();

$(window).everyTime(2000, function() {
    OurChildren.riseAStar();
});

})();

